version: "3"
services:
#/*SOFKA SERVICES
  transaction-service:
    build: ../sofka-transaction-service
    environment:
      - PORT=8080
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - 8080:8080
    depends_on:
      - kafka
  transaction-consumer1:
    build: ../sofka-transaction-consumer
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MONGO_HOST=mongo
    depends_on:
      - kafka
      - mongo
  transaction-consumer2:
    build: ../sofka-transaction-consumer
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MONGO_HOST=mongo
    depends_on:
      - kafka
      - mongo
  transaction-consumer3:
    build: ../sofka-transaction-consumer
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MONGO_HOST=mongo
    depends_on:
      - kafka
      - mongo
#SOFKA SERVICES*/

#/* KAFKA CLUSTER
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8090:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

#KAFKA CLUSTER */

#/* MONGODB CLUSTER
  mongo:
    image: mongo:6
    hostname: mongo
    container_name: mongo
    ports:
      - 27017:27017
    entrypoint: ["mongod", "--bind_ip", "localhost,mongo"]
#MONGODB CLUSTER */